---
name: 'toolchain-action'
author: 'Open Orbis'
description: 'Generates a compiled FPKG file ready for installation on a homebrew enabled Sony PlayStation 4 system'
inputs:
  version:
    description: 'The toolchain version to use within the docker container'
    require: false
    default: 'latest'
  command:
    description: 'The command to run in your project directory'
    required: true
runs:
  using: 'docker'
  image: './Dockerfile'
branding:
  icon: 'link'
  color: 'blue'
